# Generated by Django 4.2.8 on 2023-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member", name="age", field=models.IntegerField(null=True),
        ),
    ]
