# Generated by Django 4.2.8 on 2023-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("GR", "Grass"),
                            ("HD", "Hard"),
                            ("CL", "Clay"),
                            ("CP", "Carpet"),
                        ],
                        max_length=2,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
            ],
        ),
    ]
